import java.awt.HeadlessException;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/
/**
*
* @author AKSHITHA
*/
public class accountdetails extends javax.swing.JFrame {
 /**
 * Creates new form accountdetails
*/
 public accountdetails() {
 initComponents();
 }
 public accountdetails(String ms) {
 initComponents();
 a1.setText(ms);
 }
 /**
 * This method is called from within the constructor to initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is always
 * regenerated by the Form Editor.
 */
 @SuppressWarnings("unchecked")
 // <editor-fold defaultstate="collapsed" desc="Generated Code">
 private void initComponents() {
 jLabel1 = new javax.swing.JLabel();
 jLabel2 = new javax.swing.JLabel();
 jLabel3 = new javax.swing.JLabel();
 jLabel4 = new javax.swing.JLabel();
 jLabel5 = new javax.swing.JLabel();
 jLabel6 = new javax.swing.JLabel();
 jButton1 = new javax.swing.JButton();
 a1 = new javax.swing.JLabel();
 b1 = new javax.swing.JLabel();
 c1 = new javax.swing.JLabel();
 d1 = new javax.swing.JLabel();
 e1 = new javax.swing.JLabel();
 jButton2 = new javax.swing.JButton();
 jLabel7 = new javax.swing.JLabel();

setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
getContentPane().setLayout(null);
 jLabel1.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
 jLabel1.setForeground(new java.awt.Color(255, 255, 255));
 jLabel1.setText("Account details");
 getContentPane().add(jLabel1);
 jLabel1.setBounds(160, 10, 170, 30);
 jLabel2.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
 jLabel2.setForeground(new java.awt.Color(255, 255, 255));
 jLabel2.setText("Account number:");
 getContentPane().add(jLabel2);
 jLabel2.setBounds(54, 63, 130, 30);
 jLabel3.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
 jLabel3.setForeground(new java.awt.Color(255, 255, 255));
 jLabel3.setText("Account name:");
 getContentPane().add(jLabel3);
 jLabel3.setBounds(54, 101, 120, 30);
 jLabel4.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
 jLabel4.setForeground(new java.awt.Color(255, 255, 255));
 jLabel4.setText("Branch name:");
 getContentPane().add(jLabel4);
 jLabel4.setBounds(54, 143, 120, 30);
 jLabel5.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
 jLabel5.setForeground(new java.awt.Color(255, 255, 255));
 jLabel5.setText("Branch id:");
 getContentPane().add(jLabel5);
 jLabel5.setBounds(54, 185, 100, 30);
 jLabel6.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
 jLabel6.setForeground(new java.awt.Color(255, 255, 255));
 jLabel6.setText("Phone number:");
getContentPane().add(jLabel6);
 jLabel6.setBounds(54, 226, 120, 30);
 jButton1.setBackground(new java.awt.Color(153, 0, 153));
 jButton1.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
 jButton1.setForeground(new java.awt.Color(255, 255, 255));
 jButton1.setText("go back");
 jButton1.addActionListener(new java.awt.event.ActionListener() {
 public void actionPerformed(java.awt.event.ActionEvent evt) {
 jButton1ActionPerformed(evt);
 }
 });
 getContentPane().add(jButton1);
 jButton1.setBounds(190, 290, 90, 23);
 a1.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
 a1.setForeground(new java.awt.Color(255, 255, 255));
 getContentPane().add(a1);
 a1.setBounds(210, 60, 160, 30);
 b1.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
 b1.setForeground(new java.awt.Color(255, 255, 255));
 getContentPane().add(b1);
 b1.setBounds(210, 90, 160, 30);
 c1.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
 c1.setForeground(new java.awt.Color(255, 255, 255));
 getContentPane().add(c1);
 c1.setBounds(210, 140, 180, 30);
 d1.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
 d1.setForeground(new java.awt.Color(255, 255, 255));
 getContentPane().add(d1);
 d1.setBounds(210, 180, 180, 30);
e1.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
 e1.setForeground(new java.awt.Color(255, 255, 255));
 getContentPane().add(e1);
 e1.setBounds(210, 220, 220, 30);
 jButton2.setBackground(new java.awt.Color(102, 0, 102));
 jButton2.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
 jButton2.setForeground(new java.awt.Color(255, 255, 255));
 jButton2.setText("GET DETAILS");
 jButton2.addActionListener(new java.awt.event.ActionListener() {
 public void actionPerformed(java.awt.event.ActionEvent evt) {
 jButton2ActionPerformed(evt);
 }
 });
 getContentPane().add(jButton2);
 jButton2.setBounds(390, 60, 170, 40);
 jLabel7.setIcon(new
javax.swing.ImageIcon(getClass().getResource("/purple-pink-abstractbackground-polygon-vector-1681461.jpg"))); // NOI18N
 getContentPane().add(jLabel7);
 jLabel7.setBounds(0, 0, 580, 360);
 pack();
 }// </editor-fold>
 private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
 this.setVisible(false);
 new menuclass().setVisible(true);
 }
 private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
 // TODO add your handling code here:
 try {
Class.forName("org.apache.derby.jdbc.EmbeddedDriver");
 java.sql.Connection
con=DriverManager.getConnection("jdbc:derby:C:\\Users\\AKSHITHA\\.netbean
s-derby\\Akshitha", "AKS","AKS");
 java.sql.Statement stmt=con.createStatement();
 String DBQ="Select * from AKS.account where
acc_no='"+a1.getText()+"'";
 ResultSet rs=stmt.executeQuery(DBQ);
 if (rs.next())
 {
 a1.setText(rs.getString(1));
 b1.setText(rs.getString(2));
 c1.setText(rs.getString(3));
 d1.setText(rs.getString(4));
 e1.setText(rs.getString(5));
 }



 }catch (ClassNotFoundException | SQLException | HeadlessException e){
 System.out.println(e);

 }
 }
 /**
 * @param args the command line arguments
 */
 public static void main(String args[]) {
 /* Set the Nimbus look and feel */
 //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code
(optional) ">
 /* If Nimbus (introduced in Java SE 6) is not available, stay with the default
look and feel.
 * For details see 
*/
 try {
 for (javax.swing.UIManager.LookAndFeelInfo info :
javax.swing.UIManager.getInstalledLookAndFeels()) {
 if ("Nimbus".equals(info.getName())) {
 javax.swing.UIManager.setLookAndFeel(info.getClassName());
 break;
 }
 }
 } catch (ClassNotFoundException ex) {

java.util.logging.Logger.getLogger(accountdetails.class.getName()).log(java.util.l
ogging.Level.SEVERE, null, ex);
 } catch (InstantiationException ex) {

java.util.logging.Logger.getLogger(accountdetails.class.getName()).log(java.util.l
ogging.Level.SEVERE, null, ex);
 } catch (IllegalAccessException ex) {

java.util.logging.Logger.getLogger(accountdetails.class.getName()).log(java.util.l
ogging.Level.SEVERE, null, ex);
 } catch (javax.swing.UnsupportedLookAndFeelException ex) {

java.util.logging.Logger.getLogger(accountdetails.class.getName()).log(java.util.l
ogging.Level.SEVERE, null, ex);
 }
 //</editor-fold>
 /* Create and display the form */
 java.awt.EventQueue.invokeLater(new Runnable() {
 public void run() {
 new accountdetails().setVisible(true);
 }
 });
}
 // Variables declaration - do not modify
 private javax.swing.JLabel a1;
 private javax.swing.JLabel b1;
 private javax.swing.JLabel c1;
 private javax.swing.JLabel d1;
 private javax.swing.JLabel e1;
 private javax.swing.JButton jButton1;
 private javax.swing.JButton jButton2;
 private javax.swing.JLabel jLabel1;
 private javax.swing.JLabel jLabel2;
 private javax.swing.JLabel jLabel3;
 private javax.swing.JLabel jLabel4;
 private javax.swing.JLabel jLabel5;
 private javax.swing.JLabel jLabel6;
 private javax.swing.JLabel jLabel7;
 // End of variables declaration
}