import java.awt.HeadlessException;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/
/**
*
* @author AKSHITHA
*/
public class fundtransfer extends javax.swing.JFrame {
 /**
 * Creates new form fundtransfer
 */
 public fundtransfer() {
 initComponents();
 }
 public fundtransfer(String c) {
 initComponents();
 a.setText(c);
 }
 /**
 * This method is called from within the constructor to initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is always
 * regenerated by the Form Editor.
 */
 @SuppressWarnings("unchecked")
 // <editor-fold defaultstate="collapsed" desc="Generated Code">
 private void initComponents() {
 jLabel1 = new javax.swing.JLabel();
 jLabel3 = new javax.swing.JLabel();
 jLabel4 = new javax.swing.JLabel();
 jButton1 = new javax.swing.JButton();
 mon = new javax.swing.JTextField();
 to = new javax.swing.JTextField();
 jLabel2 = new javax.swing.JLabel();
 a = new javax.swing.JLabel();
 jLabel5 = new javax.swing.JLabel();

setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
 getContentPane().setLayout(null);
 jLabel1.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
 jLabel1.setForeground(new java.awt.Color(255, 255, 255));
 jLabel1.setText("fund transfer");
 getContentPane().add(jLabel1);
 jLabel1.setBounds(140, 20, 88, 15);
 jLabel3.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
 jLabel3.setForeground(new java.awt.Color(255, 255, 255));
 jLabel3.setText("to account");
 getContentPane().add(jLabel3);
 jLabel3.setBounds(80, 80, 71, 15);
 jLabel4.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
 jLabel4.setForeground(new java.awt.Color(255, 255, 255));
 jLabel4.setText("money");
 getContentPane().add(jLabel4);
 jLabel4.setBounds(90, 140, 43, 15);
 jButton1.setBackground(new java.awt.Color(153, 0, 153));
 jButton1.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
 jButton1.setForeground(new java.awt.Color(255, 255, 255));
 jButton1.setText("MONEY TRANSFER");
 jButton1.addActionListener(new java.awt.event.ActionListener() {
 public void actionPerformed(java.awt.event.ActionEvent evt) {
 jButton1ActionPerformed(evt);
 }
 });
 getContentPane().add(jButton1);
 jButton1.setBounds(120, 210, 170, 50);
 getContentPane().add(mon);
 mon.setBounds(200, 140, 110, 30);
 getContentPane().add(to);
 to.setBounds(200, 80, 120, 30);
 jLabel2.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
 jLabel2.setForeground(new java.awt.Color(255, 255, 255));
 jLabel2.setText("USER-ID:");
 getContentPane().add(jLabel2);
 jLabel2.setBounds(244, 10, 70, 30);
 a.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
 a.setForeground(new java.awt.Color(255, 255, 255));
 getContentPane().add(a);
 a.setBounds(320, 10, 70, 30);
 jLabel5.setIcon(new
javax.swing.ImageIcon(getClass().getResource("/purple-pink-abstractbackground-polygon-vector-1681461.jpg"))); // NOI18N
 getContentPane().add(jLabel5);
 jLabel5.setBounds(0, 0, 470, 330);
 pack();
 }// </editor-fold>
 private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
 try{
 Class.forName("org.apache.derby.jdbc.EmbeddedDriver");
 java.sql.Connection
con=DriverManager.getConnection("jdbc:derby:C:\\Users\\AKSHITHA\\.netbean
s-derby\\Akshitha","AKS","AKS");
 Statement st=con.createStatement();
 String SQL="select * from aks.login where userid='"+to.getText()+"'";
 ResultSet rs=st.executeQuery(SQL);
 if(!rs.next())
 {
 JOptionPane.showMessageDialog(null,"NO SUCH ID FOUND");
 }
 else
 {
 String S="select * from aks.fund where id='"+a.getText()+"'";
 String B="select * from aks.fund where id='"+to.getText()+"'";
 int z=Integer.parseInt(mon.getText());
 rs=st.executeQuery(S);
 if(rs.next())
 {
 int y=Integer.parseInt(rs.getString(2));
 if(z>y)
 {
 JOptionPane.showMessageDialog(null,"INSUFFICIENT
BALANCE");
 }
 else
 {
 JOptionPane.showMessageDialog(null, "MONEY
TRANSFERED");
 int u=y-z;
 String t=Integer.toString(u);
 String f="update fund set balance='"+t+"' where
id='"+a.getText()+"'";
 PreparedStatement pst=con.prepareStatement(f);
 pst.executeUpdate();
 }
 }
 rs=st.executeQuery(B);
 if(rs.next())
 {
 int x=Integer.parseInt(rs.getString(2));
 int r=x+z;
 String o=Integer.toString(r);
 String h="update fund set balance='"+o+"' where
id='"+to.getText()+"'";
 PreparedStatement pst=con.prepareStatement(h);
 pst.executeUpdate();
 }


 }
 con.close();
 }
 catch(ClassNotFoundException | SQLException | HeadlessException |
NumberFormatException e)
 {
 System.err.println(e);
 }
 }
 /**
 * @param args the command line arguments
 */
 public static void main(String args[]) {
 /* Set the Nimbus look and feel */
 //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code
(optional) ">
 /* If Nimbus (introduced in Java SE 6) is not available, stay with the default
look and feel.
 * For details see
http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
 */
 try {
 for (javax.swing.UIManager.LookAndFeelInfo info :
javax.swing.UIManager.getInstalledLookAndFeels()) {
 if ("Nimbus".equals(info.getName())) {
 javax.swing.UIManager.setLookAndFeel(info.getClassName());
 break;
 }
 }
 } catch (ClassNotFoundException ex) {

java.util.logging.Logger.getLogger(fundtransfer.class.getName()).log(java.util.log
ging.Level.SEVERE, null, ex);
 } catch (InstantiationException ex) {

java.util.logging.Logger.getLogger(fundtransfer.class.getName()).log(java.util.log
ging.Level.SEVERE, null, ex);
 } catch (IllegalAccessException ex) {

java.util.logging.Logger.getLogger(fundtransfer.class.getName()).log(java.util.log
ging.Level.SEVERE, null, ex);
 } catch (javax.swing.UnsupportedLookAndFeelException ex) {

java.util.logging.Logger.getLogger(fundtransfer.class.getName()).log(java.util.log
ging.Level.SEVERE, null, ex);
 }
 //</editor-fold>
 /* Create and display the form */
 java.awt.EventQueue.invokeLater(new Runnable() {
 public void run() {
 new fundtransfer().setVisible(true);
 }
 });
 }
 // Variables declaration - do not modify
 private javax.swing.JLabel a;
 private javax.swing.JButton jButton1;
 private javax.swing.JLabel jLabel1;
 private javax.swing.JLabel jLabel2;
 private javax.swing.JLabel jLabel3;
 private javax.swing.JLabel jLabel4;
 private javax.swing.JLabel jLabel5;
 private javax.swing.JTextField mon;
 private javax.swing.JTextField to;
 // End of variables declaration 
