import java.awt.HeadlessException;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/
/**
*
* @author AKSHITHA
*/
public class loginclass extends javax.swing.JFrame {
 /**
 * Creates new form loginclass
 */
 public loginclass() {
 initComponents();
 }
 /**
 * This method is called from within the constructor to initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is always
 * regenerated by the Form Editor.
 */
 @SuppressWarnings("unchecked")
 // <editor-fold defaultstate="collapsed" desc="Generated Code">
 private void initComponents() {
 jLabel1 = new javax.swing.JLabel();
 jLabel2 = new javax.swing.JLabel();
 jLabel3 = new javax.swing.JLabel();
 userText = new javax.swing.JTextField();
 passText = new javax.swing.JPasswordField();
 jButton1 = new javax.swing.JButton();
 jLabel4 = new javax.swing.JLabel();

setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
setMinimumSize(new java.awt.Dimension(557, 373));
 setPreferredSize(new java.awt.Dimension(557, 373));
 getContentPane().setLayout(null);
 jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
 jLabel1.setForeground(new java.awt.Color(255, 255, 255));
 jLabel1.setText("Username:");
 getContentPane().add(jLabel1);
 jLabel1.setBounds(50, 140, 74, 17);
 jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
 jLabel2.setForeground(new java.awt.Color(255, 255, 255));
 jLabel2.setText("Password:");
 getContentPane().add(jLabel2);
 jLabel2.setBounds(50, 180, 72, 17);
 jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
 jLabel3.setForeground(new java.awt.Color(255, 255, 255));
 jLabel3.setText("LOGIN");
 getContentPane().add(jLabel3);
 jLabel3.setBounds(240, 50, 70, 50);
 userText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
 userText.addActionListener(new java.awt.event.ActionListener() {
 public void actionPerformed(java.awt.event.ActionEvent evt) {
 userTextActionPerformed(evt);
 }
 });
 getContentPane().add(userText);
 userText.setBounds(170, 130, 210, 30);
 passText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
 getContentPane().add(passText);
 passText.setBounds(170, 170, 210, 30);
jButton1.setBackground(new java.awt.Color(0, 153, 51));
 jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
 jButton1.setText("Submit");
 jButton1.addActionListener(new java.awt.event.ActionListener() {
 public void actionPerformed(java.awt.event.ActionEvent evt) {
 jButton1ActionPerformed(evt);
 }
 });
 getContentPane().add(jButton1);
 jButton1.setBounds(170, 210, 210, 30);
 jLabel4.setIcon(new
javax.swing.ImageIcon(getClass().getResource("/transparent_organic_form_2136
56.jpg"))); // NOI18N
 getContentPane().add(jLabel4);
 jLabel4.setBounds(0, 0, 540, 360);
 pack();
 }// </editor-fold>
 private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
 try
 {
 Class.forName("org.apache.derby.jdbc.EmbeddedDriver");
 java.sql.Connection
con=DriverManager.getConnection("jdbc:derby:C:\\Users\\AKSHITHA\\.netbean
s-derby\\Akshitha","AKS","AKS");
 Statement st=con.createStatement();
 String DBQ= "Select * from AKS.LOGIN where
USERID='"+userText.getText()+"' AND PASSWORD='"+passText.getText()+"'
";

 ResultSet rs=st.executeQuery(DBQ);
 if (rs.next()) 
{
 String msg=userText.getText();
 this.setVisible(false);
 new menuclass(msg).setVisible(true);
 }
 else
 JOptionPane.showMessageDialog(null,"invalid login details ");
 }catch(ClassNotFoundException | SQLException | HeadlessException ae){
 System.out.println(ae);

 }

 }
 private void userTextActionPerformed(java.awt.event.ActionEvent evt) {
 // TODO add your handling code here:
 }
 /**
 * @param args the command line arguments
 */
 public static void main(String args[]) {
 /* Set the Nimbus look and feel */
 //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code
(optional) ">
 /* If Nimbus (introduced in Java SE 6) is not available, stay with the default
look and feel.
 * For details see
http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
 */
 try {
 for (javax.swing.UIManager.LookAndFeelInfo info :
javax.swing.UIManager.getInstalledLookAndFeels()) {
 if ("Nimbus".equals(info.getName())) {
javax.swing.UIManager.setLookAndFeel(info.getClassName());
 break;
 }
 }
 } catch (ClassNotFoundException ex) {

java.util.logging.Logger.getLogger(loginclass.class.getName()).log(java.util.loggi
ng.Level.SEVERE, null, ex);
 } catch (InstantiationException ex) {

java.util.logging.Logger.getLogger(loginclass.class.getName()).log(java.util.loggi
ng.Level.SEVERE, null, ex);
 } catch (IllegalAccessException ex) {

java.util.logging.Logger.getLogger(loginclass.class.getName()).log(java.util.loggi
ng.Level.SEVERE, null, ex);
 } catch (javax.swing.UnsupportedLookAndFeelException ex) {

java.util.logging.Logger.getLogger(loginclass.class.getName()).log(java.util.loggi
ng.Level.SEVERE, null, ex);
 }
 //</editor-fold>
 /* Create and display the form */
 java.awt.EventQueue.invokeLater(new Runnable() {
 public void run() {
 new loginclass().setVisible(true);
 }
 });
 }
 // Variables declaration - do not modify
 private javax.swing.JButton jButton1;
 private javax.swing.JLabel jLabel1;
 private javax.swing.JLabel jLabel2;
 private javax.swing.JLabel jLabel3;
 private javax.swing.JLabel jLabel4;
 private javax.swing.JPasswordField passText;
 private javax.swing.JTextField userText;
 // End of variables declaration
}
