/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/
/**
*
* @author AKSHITHA
*/
public class menuclass extends javax.swing.JFrame {
 /**
 * Creates new form menuclass
 */
 public menuclass() {
 initComponents();
 }
 public menuclass(String b) {
 initComponents();
 a.setText(b);
 }
 /**
* This method is called from within the constructor to initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is always
 * regenerated by the Form Editor.
 */
 @SuppressWarnings("unchecked")
 // <editor-fold defaultstate="collapsed" desc="Generated Code">
 private void initComponents() {
 jButton1 = new javax.swing.JButton();
 jButton2 = new javax.swing.JButton();
 a = new javax.swing.JLabel();
 jLabel1 = new javax.swing.JLabel();
 jButton4 = new javax.swing.JButton();
 jLabel2 = new javax.swing.JLabel();

setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
 getContentPane().setLayout(null);
 jButton1.setBackground(new java.awt.Color(153, 0, 153));
 jButton1.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
 jButton1.setForeground(new java.awt.Color(255, 255, 255));
 jButton1.setText("Account details");
 jButton1.addActionListener(new java.awt.event.ActionListener() {
 public void actionPerformed(java.awt.event.ActionEvent evt) {
 jButton1ActionPerformed(evt);
 }
 });
 getContentPane().add(jButton1);
 jButton1.setBounds(60, 130, 137, 60);
 jButton2.setBackground(new java.awt.Color(153, 0, 153));
 jButton2.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
 jButton2.setForeground(new java.awt.Color(255, 255, 255));
 jButton2.setText("Fund Transfer");
jButton2.addActionListener(new java.awt.event.ActionListener() {
 public void actionPerformed(java.awt.event.ActionEvent evt) {
 jButton2ActionPerformed(evt);
 }
 });
 getContentPane().add(jButton2);
 jButton2.setBounds(240, 130, 150, 60);
 a.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
 a.setForeground(new java.awt.Color(255, 255, 255));
 getContentPane().add(a);
 a.setBounds(200, 10, 70, 30);
 jLabel1.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
 jLabel1.setForeground(new java.awt.Color(255, 255, 255));
 jLabel1.setText("USER-ID:");
 getContentPane().add(jLabel1);
 jLabel1.setBounds(130, 10, 60, 30);
 jButton4.setBackground(new java.awt.Color(153, 0, 153));
 jButton4.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
 jButton4.setForeground(new java.awt.Color(255, 255, 255));
 jButton4.setText("sign out");
 jButton4.addActionListener(new java.awt.event.ActionListener() {
 public void actionPerformed(java.awt.event.ActionEvent evt) {
 jButton4ActionPerformed(evt);
 }
 });
 getContentPane().add(jButton4);
 jButton4.setBounds(290, 10, 110, 30);
 jLabel2.setIcon(new
javax.swing.ImageIcon(getClass().getResource("/purple-pink-abstractbackground-polygon-vector-1681461.jpg"))); // NOI18N
 jLabel2.setMinimumSize(new java.awt.Dimension(482, 327));jLabel2.setPreferredSize(new java.awt.Dimension(482, 327));
 getContentPane().add(jLabel2);
 jLabel2.setBounds(0, 0, 480, 330);
 pack();
 }// </editor-fold>
 private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
 this.setVisible(false);
 String msg=a.getText();
 new accountdetails(msg).setVisible(true);
 }
 private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
 // TODO add your handling code here:
 this.setVisible(false);
 String msg=a.getText();
 new fundtransfer(msg).setVisible(true);
 }
 private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
 // TODO add your handling code here:
 this.setVisible(false);
 new loginclass().setVisible(true);
 }
 /**
 * @param args the command line arguments
 */
 public static void main(String args[]) {
 /* Set the Nimbus look and feel */
 //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code
(optional) ">
 /* If Nimbus (introduced in Java SE 6) is not available, stay with the default
look and feel.
* For details see
http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
 */
 try {
 for (javax.swing.UIManager.LookAndFeelInfo info :
javax.swing.UIManager.getInstalledLookAndFeels()) {
 if ("Nimbus".equals(info.getName())) {
 javax.swing.UIManager.setLookAndFeel(info.getClassName());
 break;
 }
 }
 } catch (ClassNotFoundException ex) {

java.util.logging.Logger.getLogger(menuclass.class.getName()).log(java.util.loggi
ng.Level.SEVERE, null, ex);
 } catch (InstantiationException ex) {

java.util.logging.Logger.getLogger(menuclass.class.getName()).log(java.util.loggi
ng.Level.SEVERE, null, ex);
 } catch (IllegalAccessException ex) {

java.util.logging.Logger.getLogger(menuclass.class.getName()).log(java.util.loggi
ng.Level.SEVERE, null, ex);
 } catch (javax.swing.UnsupportedLookAndFeelException ex) {

java.util.logging.Logger.getLogger(menuclass.class.getName()).log(java.util.loggi
ng.Level.SEVERE, null, ex);
 }
 //</editor-fold>
 /* Create and display the form */
 java.awt.EventQueue.invokeLater(new Runnable() {
 public void run() {
 new menuclass().setVisible(true);
 }
});
 }
 // Variables declaration - do not modify
 private javax.swing.JLabel a;
 private javax.swing.JButton jButton1;
 private javax.swing.JButton jButton2;
 private javax.swing.JButton jButton4;
 private javax.swing.JLabel jLabel1;
 private javax.swing.JLabel jLabel2;
 // End of variables declaration
}
